### ISSUE TITLE
Package recorded with no `name`

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-node#104]
This data was captured from https://github.com/getappmap/appmap-services/tree/feat/speak-api with a default appmap.yml

```yaml
name: api-service
appmap_dir: tmp/appmap
packages:
  - path: .
    exclude:
      - node_modules
      - .yarn
```

See the example AppMap attached.

[2024-01-25T20:17:31.404Z_-v1-ai-speak.appmap.zip](https://github.com/getappmap/appmap-node/files/14057497/2024-01-25T20.17.31.404Z_-v1-ai-speak.appmap.zip)
