### ISSUE TITLE
AppMap folder exclusion isn't working with pnpm

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-node#111]
Using the Bluesky social app with the `appmap` branch here: https://github.com/land-of-apps/social-app/blob/appmap/

[Following these steps to get the application running: ](https://github.com/land-of-apps/social-app/blob/appmap/docs/build.md)

Once I get to "Start the dev servers"
I would run: `cd packages/dev-env && pnpm start`

And then I would run the dev app also: `yarn web`

Would confirm the appmap.yml was being read in
```
 (cd atproto/packages/dev-env && npx appmap-node pnpm start)
(Λ) Running with appmap-node version 2.15.0
(Λ) Using config file /Users/petecheslock/repos/social-app/appmap.yml
```

but then i would get maps that included `node_modules/.pnpm`
<img width="869" alt="Screenshot 2024-02-07 at 11 52 45 AM" src="https://github.com/getappmap/appmap-node/assets/511733/0bf20fbb-f790-46c0-a039-009766606836">

I've tried excluding `node_modules` in different ways

```
name: social-app
appmap_dir: tmp/appmap
packages:
  - path: atproto/
    exclude:
      - node_modules
      - node_modules/.pnpm
  - path: .
    exclude:
      - atproto/node_modules
      - node_modules
      - .yarn
```

This happens when running the atproto backend so i put an `appmap.yml` file in there that says:
```
name: atproto
appmap_dir: ../tmp/appmap
packages:
  - path: .
    exclude:
      - node_modules
      - node_modules/.pnpm
```

ran the app
```
(cd atproto/packages/dev-env && npx appmap-node pnpm start)
(Λ) Running with appmap-node version 2.15.0
(Λ) Using config file /Users/petecheslock/repos/social-app/atproto/appmap.yml
```

but got the same result.
