### ISSUE TITLE
SQL with Prisma client are not being recorded by AppMap

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-node#127]
Using the latest release of [Cal.com](https://github.com/calcom/cal.com)

Using `appmap-node` version `2.18.0`

Using the default appmap.yml

```
name: calcom-monorepo
appmap_dir: tmp/appmap
packages:
  - path: .
    exclude:
      - node_modules
      - .yarn
```

When interacting with the application to create AppMaps with DB queries we are unable to see the SQL and instead the DB interactions are represented within the AppMap strangely.

<img width="1549" alt="Screenshot 2024-03-15 at 1 29 54 PM" src="https://github.com/getappmap/appmap-node/assets/511733/9bb0affe-71a9-45fa-9c39-3fe9b9097cd7">

[Further replicated in this Loom video](https://www.loom.com/share/6906d8fda0dd434d8f2f4e86103a3133)
